name: Trigger Netlify Build
on:
  schedule:
    # Run at 0601 daily
    - cron: '0 0 * * 0'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.BUILD_HOOK }}